import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../src/components/Header'
// import styles from '../styles/Home.module.css'
// import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>RPG 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </div>
  )
}

export default Home
